
name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update package index
        run:  sudo apt update
      - name: Install packages
        run:  sudo apt install -y git make sqlite3
      - name: Fetch submodules manually
        run:  git submodule update --init --recursive || true
      - name: Build with make
        run:  make -C Contents
      - name: Upload built directory
        uses: actions/upload-artifact@v2
        with:
          name: GoByExample.docset
          path: ./
